### PR TITLE
Implements basic router

### LINKED ISSUE #4: Routing
So far, we've talked about showing characters and series. I'm planning on implementing react-router. I've used it before and it works well. 

Are we showing characters on the index?

Just wondering what the routes should be at this point. 
So we might have a structure that looks like this:

```
-index
    -characters/<letter> (which <a> doubles as the index)
          -characters/<id>/profile
    -series/<letter>
          -series/<id>/detail
```

### PR DESCRIPTION
**Pull request by nicrocs**
We need a way to view different characters based on routes. This implements that. You can now view characters starting with b by going to /#/characters/b. The hash is necessary for github pages. We can adjust if we decide to use something else.

Next, I can implement linking.

Closes #4.

### CODE REVIEW

**Comment by vacas5** [comment]
some conflicts but otherwise looks super

**Comment by nicrocs** [comment]
ok, I rebased. Should be good to go now.

**Comment by vacas5** [comment]
also, just checking, but check out the info for using GitHub pages. Will this router be compliant?

https://github.com/vacas5/marvel#github-pages

Note that GitHub Pages doesn't support routers that use the HTML5 pushState history API under the hood (for example, React Router using browserHistory). This is because when there is a fresh page load for a url like http://user.github.io/todomvc/todos/42, where /todos/42 is a frontend route, the GitHub Pages server returns 404 because it knows nothing of /todos/42. If you want to add a router to a project hosted on GitHub Pages, here are a couple of solutions:

**Comment by nicrocs** [comment]
Yep, I used hashHistory instead of browser history

**Comment by nicrocs** [comment]
@vacas5 feel free to merge if you're good with that.

**Pull request merged**
